
- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Download Google Chrome
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
  tags: chrome

- name: Install Google Chrome
  ansible.builtin.apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
    state: present
  tags: chrome

- name: Download Google Chrome Driver
  get_url:
    url: "https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.78/linux64/chrome-headless-shell-linux64.zip"
    dest: /tmp/chromedriver.zip

- name: Unzip Chrome Driver
  unarchive:
    src: /tmp/chromedriver.zip
    dest: /usr/local/bin
    remote_src: yes