---
- name: install maven
  ansible.builtin.apt:
    update_cache: yes
    name: maven
    state: latest

- name: Install git
  apt:
    name: git
    state: present
  become: yes

- name: Clone the pertclinic repository
  ansible.builtin.git:
    repo: https://github.com/sennahoj123/pertclinic/tree/pet-iede
    dest: /opt/pertclinic
    single_branch: yes
    update: yes
    force: yes

- name: Set permissions recursively
  ansible.builtin.file:
    path: /opt/pertclinic
    owner: adminuser
    group: adminuser
    recurse: yes
    state: directory
  become: yes
