---
- name: install maven
  ansible.builtin.apt:
    update_cache: yes
    name: maven
    state: latest

- name: Install git
  apt:
    name: git
    state: present
  become: yes

- name: Change ownership of opt directory
  ansible.builtin.file:
    path: /opt
    owner: adminuser
    group: adminuser
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Clone the pertclinic repository
  ansible.builtin.git:
    repo: https://github.com/sennahoj123/pertclinic.git
    dest: /opt/pertclinic
    version: origin/pet-iede
    update: yes
    force: yes

- name: Set permissions recursively
  ansible.builtin.file:
    path: /opt/pertclinic
    owner: adminuser
    group: adminuser
    recurse: yes
    state: directory
  become: yes
