---
- name: install maven
  ansible.builtin.apt:
    update_cache: yes
    name: maven
    state: latest

- name: git clone pertclinic
  ansible.builtin.git:
    repo: https://github.com/sennahoj123/pertclinic
    dest: /tmp/pertclinic
    update: no 

- name: build war
  shell:
    chdir: /tmp/pertclinic
    cmd: mvn clean package
