---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes
    
- name: Download Tomcat
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
    dest: /tmp/
- name: Extract Tomcat
  unarchive:
    src: /tmp/apache-tomcat-9.0.54.tar.gz
    dest: /opt/
    remote_src: yes

