- name: Update the System Packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Create a Tomcat User
  user:
    name: tomcat

- name: Create a Tomcat Group
  group:
    name: tomcat

- name: Create a Tomcat Directory
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: 755
    recurse: yes

- name: download & unarchive tomcat
  unarchive:
    src: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Change ownership of tomcat directory
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Creating a service file
  become: yes
  copy:
    dest: /etc/systemd/system/tomcat.service 
    content: |
      [Unit]
      Description=Tomcat Service
      Requires=network.target
      After=network.target
      [Service]
      Type=forking
      User=tomcat
      Environment="CATALINA_PID=/opt/tomcat/logs/tomcat.pid"
      Environment="CATALINA_BASE=/opt/tomcat"
      Environment="CATALINA_HOME=/opt/tomcat"
      Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
      ExecStart=/opt/tomcat/bin/startup.sh
      ExecStop=/opt/tomcat/bin/shutdown.sh
      Restart=on-abnormal
      [Install]
      WantedBy=multi-user.target
  
- name: Start and Enable Tomcat on sever
  ansible.builtin.systemd_service:
    name: tomcat
    state: started
    daemon_reload: true