- name: Ensure apt-transport-https is installed
  ansible.builtin.shell: apt-get install apt-transport-https -y

- name: Add Elastic GPG key
  ansible.builtin.shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -

- name: Add Elastic repository to sources list
  ansible.builtin.shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-7.x.list

- name: Update apt cache
  ansible.builtin.shell: apt-get update -y

- name: Install Filebeat
  ansible.builtin.shell: apt-get install filebeat -y

- name: Create a backup of filebeat.yml
  ansible.builtin.command:
    cmd: cp /etc/filebeat/filebeat.yml /etc/filebeat/filebeat.yml.backup
    creates: /etc/filebeat/filebeat.yml.backup

- name: Add paths to Filebeat inputs
  ansible.builtin.blockinfile:
    path: /etc/filebeat/filebeat.yml
    block: |
      paths:
        - /var/log/*.log
        - /opt/tomcat/logs/*.log
        - /opt/tomcat/logs/*.txt
        - /opt/tomcat/logs/*.out
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: yes

- name: Comment out Logstash output section in filebeat.yml
  ansible.builtin.lineinfile:
    path: /etc/filebeat/filebeat.yml
    regexp: '^output\.logstash:'
    line: '#output.logstash:'
    state: present
    backup: yes

- name: Comment out Logstash hosts configuration
  ansible.builtin.replace:
    path: /etc/filebeat/filebeat.yml
    regexp: '^#\s*hosts:\s*\[\"localhost:5044\"\]'
    replace: '#hosts: ["localhost:5044"]'
    backup: yes

- name: Enable modules
  ansible.builtin.shell: sudo filebeat modules enable tomcat

- name: Restart Filebeat service
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
  become: yes

- name: Enable Filebeat service on boot
  ansible.builtin.systemd:
    name: filebeat
    enabled: yes
  become: yes

- name: Update apt cache
  ansible.builtin.shell: apt-get update -y

- name: Install Metricbeat
  ansible.builtin.shell: apt-get install metricbeat -y

- name: Create a backup of metricbeat.yml
  ansible.builtin.command:
    cmd: cp /etc/metricbeat/metricbeat.yml /etc/metricbeat/metricbeat.yml.backup
    creates: /etc/metricbeat/metricbeat.yml.backup

- name: Configure Metricbeat
  ansible.builtin.copy:
    src: /path/to/your/metricbeat.yml
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Metricbeat service
  become: yes

- name: Enable Metricbeat modules
  ansible.builtin.shell: metricbeat modules enable system
  notify: Restart Metricbeat service
  become: yes

- name: Restart Metricbeat service
  ansible.builtin.systemd:
    name: metricbeat
    state: restarted
    enabled: yes
  become: yes
