
- name: Add HashiCorp GPG key
  ansible.builtin.command: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: yes

- name: Add HashiCorp APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
  become: yes

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: present
  become: yes
