---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install necessary dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg
      - wget
      - unzip
    state: present
  become: yes

- name: Install Terraform
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip"
    dest: "/tmp/terraform.zip"
  become: yes

- name: Unzip Terraform
  ansible.builtin.unarchive:
    src: "/tmp/terraform.zip"
    dest: "/usr/local/bin/"
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes
  notify:
    - Terraform Installed

- name: Add Microsoft signing key
  ansible.builtin.shell: |
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
  become: yes

- name: Add Azure CLI repository
  ansible.builtin.shell: |
    AZ_REPO=$(lsb_release -cs)
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  become: yes

- name: Update apt cache and install Azure CLI
  ansible.builtin.apt:
    update_cache: yes
    name: azure-cli
    state: present
  become: yes

- name: Update apt package cache and install jq
  ansible.builtin.shell:
    cmd: sudo apt-get install -y jq

- name: Update apt repositories
  ansible.builtin.shell: sudo apt update
  become: yes

- name: Install python3-pip
  ansible.builtin.shell: sudo apt install -y python3-pip
  become: yes

- name: Upgrade Ansible using pip3
  ansible.builtin.shell: sudo pip3 install ansible --upgrade
  become: yes

- name: Install six module
  ansible.builtin.shell: pip3 install six
  become: yes

handlers:
  - name: Terraform Installed
    ansible.builtin.shell: echo "Terraform installed successfully"
