- name: Update apt package cache and install necessary dependencies
  ansible.builtin.apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: yes

- name: Download and install the Microsoft signing key
  ansible.builtin.shell: |
    sudo mkdir -p /etc/apt/keyrings
    curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
      sudo gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg
    sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
  become: yes

- name: Add the Azure CLI software repository
  ansible.builtin.shell: |
    AZ_DIST=$(lsb_release -cs)
    echo "Types: deb
    URIs: https://packages.microsoft.com/repos/azure-cli/
    Suites: ${AZ_DIST}
    Components: main
    Architectures: $(dpkg --print-architecture)
    Signed-by: /etc/apt/keyrings/microsoft.gpg" | sudo tee /etc/apt/sources.list.d/azure-cli.sources
  become: yes

- name: Update repository information and install the azure-cli package
  ansible.builtin.shell: |
    sudo apt-get update
    sudo apt-get install azure-cli
  become: yes
