- name: Install Azure CLI prerequisites
  become: yes
  shell: |
    sudo apt-get update
    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

- name: Install Azure CLI
  become: yes
  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

- name: Add Microsoft GPG key and Azure CLI repository
  become: yes
  block:
    - name: Create directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Microsoft GPG key
      shell: curl -sLS https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg
      args:
        creates: /etc/apt/keyrings/microsoft.gpg

    - name: Set permissions for Microsoft GPG key
      file:
        path: /etc/apt/keyrings/microsoft.gpg
        mode: '0644'

    - name: Add Azure CLI repository to apt sources list
      lineinfile:
        path: /etc/apt/sources.list.d/azure-cli.sources
        line: |
          Types: deb
          URIs: https://packages.microsoft.com/repos/azure-cli/
          Suites: {{ ansible_distribution_release }}
          Components: main
          Architectures: {{ ansible_architecture }}
          Signed-by: /etc/apt/keyrings/microsoft.gpg

    - name: Update apt cache
      apt:
        update_cache: yes

- name: Install Azure CLI
  become: yes
  apt:
    name: azure-cli
    state: present

- name: Install Terraform prerequisites
  become: yes
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt update

- name: Install Terraform
  become: yes
  apt:
    name: terraform
    state: present
