- name: Install Python 3
  ansible.builtin.apt:
    name: python3
    state: latest
    update_cache: yes
  become: yes

- name: Install pip for Python 3
  ansible.builtin.apt:
    name: python3-pip
    state: latest
    update_cache: yes
  become: yes

- name: Install selenium
  ansible.builtin.shell:
    cmd: pip3 install selenium --break-system-packages


- name: Install npm
  ansible.builtin.apt:
    name: npm
    state: latest
    update_cache: yes

- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: latest
    update_cache: yes

- name: Install nvm
  ansible.builtin.shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    . ~/.bashrc
  become: yes

- name: Load nvm and install Node.js
  ansible.builtin.shell: |
    . ~/.bashrc
    nvm install 20
    nvm use 20

- name: Install Selenium Side Runner
  ansible.builtin.shell: 
    cmd: npm install -g selenium-side-runner
  become: yes

- name: Create reports directory
  ansible.builtin.file:
    path: /tmp/pertclinic/reports
    state: directory
    mode: '0777'
