- name: Update apt package cache
  apt:
    update_cache: yes

- name: install Python3
  shell:
    cmd: |
    install python3 --break-system-packages
    install python3 -pip --break-system-packages

- name: Install Selenium Side Runner
  npm:
    name: selenium-side-runner
    global: yes

- name: install Python3
  shell:
    cmd: pip3 install selenium