---
- name: install python
  ansible.builtin.apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Install selenium
  ansible.builtin.pip:
    name: selenium
    state: latest


