---
- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install prerequisites for Node.js
  apt:
    name:
      - curl
    state: present

- name: Add Node.js 20 repository
  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  become: yes

- name: Install Node.js 20
  apt:
    name: nodejs
    state: present
  become: yes

- name: Ensure Node.js was installed
  command: node --version
  register: node_version_check
  failed_when: node_version_check.rc != 0

- name: update package
  shell:
    cmd: sudo apt update

- name: Install Python3 and pip
  shell:
    cmd: sudo apt-get install python-pip

- name: Install selenium using pip
  shell:
    cmd: sudo pip install selenium

- name: Install Selenium Side Runner
  npm:
    name: selenium-side-runner
    global: yes
