---
- name: install python
  ansible.builtin.apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Install selenium
  ansible.builtin.pip:
    name: selenium
    state: latest

- name: Install Node.js (if not already installed)
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Install npm (if not already installed)
  ansible.builtin.package:
    name: npm
    state: present

- name: Install Selenium Side Runner
  npm:
    name: selenium-side-runner
    global: yes
    state: present