- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Install selenium
  ansible.builtin.pip:
    name: selenium
    state: latest

- name: Install npm
  ansible.builtin.apt:
    name: npm
    state: latest
    update_cache: yes

- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: latest
    update_cache: yes

- name: Install nvm
  ansible.builtin.shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    . ~/.bashrc
  become: yes

- name: Load nvm and install Node.js
  ansible.builtin.shell: |
    . ~/.bashrc
    nvm install 16
    nvm use 16
    nvm alias default 16
  become: yes
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    USER: "{{ ansible_env.USER }}"
    HOME: "{{ ansible_env.HOME }}"

- name: Install Selenium Side Runner
  ansible.builtin.shell: 
    cmd: npm install -g selenium-side-runner
  become: yes

- name: Create reports directory
  ansible.builtin.file:
    path: /tmp/pertclinic/reports
    state: directory
    mode: '0777'
