- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install prerequisites for Node.js
  ansible.builtin.apt:
    name: curl
    state: present
  become: yes

- name: Add Node.js 20 repository
  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  become: yes

- name: Install Node.js 20
  ansible.builtin.apt:
    name: nodejs
    state: present
  become: yes

- name: Ensure Node.js was installed
  ansible.builtin.command: node --version
  register: node_version_check
  failed_when: node_version_check.rc != 0

- name: Install Python 3
  ansible.builtin.apt:
    name: python3
    state: present
  become: yes

- name: Ignore PEP 668 because it's silly.
  ansible.builtin.file:
    path: /usr/lib/python3.12/EXTERNALLY-MANAGED
    state: absent

- name: Install pip for Python 3
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: yes

- name: Install selenium using pip
  ansible.builtin.pip:
    name: selenium
    executable: pip3

- name: Install Selenium Side Runner
  ansible.builtin.npm:
    name: selenium-side-runner
    global: yes
    state: present
  become: yes
