---
- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install prerequisites for Node.js
  apt:
    name:
      - curl
    state: present

- name: Install Node.js and npm
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    apt-get install -y nodejs

- name: Install Python3 and pip
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install selenium using pip
  shell: |
    pip3 install selenium --break-system-packages

- name: Install Selenium Side Runner
  npm:
    name: selenium-side-runner
    global: yes
