---
- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install prerequisites for Node.js
  apt:
    name:
      - curl
    state: present

- name: Install Node.js and npm
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    apt-get install -y nodejs

- name: Install Python3, pip, and venv
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: install selenium
    shell:
        cmd: pip install selenium --break-system-packages


- name: Install Selenium Side Runner
  npm:
    name: selenium-side-runner
    global: yes

- name: Create a Python virtual environment
  command: python3 -m venv /opt/selenium_env

- name: Install Selenium Python package in virtual environment
  command: /opt/selenium_env/bin/pip install selenium
