---
- name: Download Action runner
  get_url:
    url: https://github.com/actions/runner/releases/download/v2.308.0/actions-runner-linux-x64-2.308.0.tar.gz
    dest: /tmp/
- name: Extract runner
  unarchive:
    src: /tmp/actions-runner-linux-x64-2.308.0.tar.gz
    dest: /opt/
    remote_src: yes
- name: Set executable permissions for run.sh
  ansible.builtin.file:
    path: /opt/run.sh
    owner: root
    group: root 
    mode: '777'
- name: Run the runner
  shell: /opt/run.sh