## mian playbook to execute alles
- name: install testing en deplopy petclinic
  hosts: azure_vm
  become: yes
  remote_user: azureuser
  roles:
    - Install-jmeter
    - Install-github-runner
    - Install-tomcat
    - Install-openJDK
    - Install-selenium
    - Install-maven
    - Install-docker
  

  
