## mian playbook to execute alles
- name: install testing en deplopy petclinic
  hosts: azure_vm
  become: yes
  remote_user: azureuser
  roles:
    - include: main-acceptance.yml

    #- Install-openJDK
    #- Install-terraform&azure-cli
    #- Install-ansi
    #- Install-firefox
    #- Install-github-runner
    #- Install-docker
    #- Install-tomcat
    #- Install-maven
    #- Install-jmeter
    #- Install-selenium