## playbook to build
- name: install
  hosts: ElastikVM
  become: yes
  remote_user: adminuser
  roles:
    - Install-openJDK
    #- Install-maven
    #- Install-jmeter
    #- Install-terraform&azure-cli
    #- Install-ansi
    #- Install-chrome
    #- Install-github-runner
    #- Install-docker
    #- Install-tomcat
    #- Install-selenium
    - Install-ELK_slack

    sudo metricbeat setup --index-management -E 'output.elasticsearch.hosts=["localhost:9200"]'
    sudo metricbeat setup -e -E output.elasticsearch.hosts=['localhost:9200'] -E setup.kibana.host=localhost:5601
 