## playbook to build
- name: install
  hosts: provisioningvm
  become: yes
  remote_user: adminuser
  roles:
    - Install-openJDK
    #- Install-maven
    #- Install-jmeter
    - Install-terraform&azure-cli
    - Install-ansi
    #- Install-chrome
    - Install-github-runner
    #- Install-docker
    #- Install-tomcat
    #- Install-selenium
    - Install-ELK_slack
    - Install-firebeat

  tasks:
    - name: Ensure the .ssh directory exists
      file:
        path: /home/adminuser/.ssh
        state: directory
        mode: '0700'
        owner: adminuser
        group: adminuser

    - name: Generate SSH key if it does not exist
      shell: |
        if [ ! -f /home/adminuser/.ssh/id_rsa ]; then
          ssh-keygen -t rsa -N "" -f /home/adminuser/.ssh/id_rsa
        fi
      args:
        creates: /home/adminuser/.ssh/id_rsa

    - name: Ensure correct permissions for the SSH private key
      file:
        path: /home/adminuser/.ssh/id_rsa
        owner: adminuser
        group: adminuser
        mode: '0600'
      
    - name: Ensure correct permissions for the SSH public key
      file:
        path: /home/adminuser/.ssh/id_rsa.pub
        owner: adminuser
        group: adminuser
        mode: '0644'