## playbook to execute deploy vm
- name: install testing vm
  hosts: Production
  become: yes
  remote_user: adminuser
  roles:
    - Install-openJDK
    - Install-maven
    #- Install-jmeter
    - Install-terraform&azure-cli
    # - Install-ansi
    #- Install-chrome
    #- Install-github-runner
    #- Install-docker
    #- Install-tomcat
    #- Install-selenium
