- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Python 3
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install pip for Python 3
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Docker Python package
  ansible.builtin.apt:
    name: python3-docker
    state: latest

- name: Install Docker
  ansible.builtin.package:
    name: docker.io
    state: present
