- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Python 3
  ansible.builtin.apt:
    name: python3
    state: present
    
- name: install apt-transport-https
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

- name: Debug - Check network connectivity
  ansible.builtin.debug:
    msg: "Testing connectivity to Docker GPG key URL"
  # Add tasks here to test network connectivity, e.g., ping or curl
  
- name: Add signing key
  ansible.builtin.shell:
    cmd: wget https://download.docker.com/linux/ubuntu/gpg
    state: present
    validate_certs: no

- name: Debug - Check GPG key presence
  ansible.builtin.debug:
    msg: "Verifying if Docker GPG key is present in the keyring"
  # Add tasks here to list GPG keys and check if Docker key is present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker.list

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: latest
    update_cache: true
