name: build provisioningVM
on:
  push:

jobs:
  maven-build:
    name: Build provisioningVM
    runs-on: local runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Where am I
        run: pwd
      - name: Run terraform init
        run: terraform init
      - name: Run terraform plan
        run: terraform plan
      - name: Run terraform apply -auto-approve
        run: terraform apply -auto-approve
