name: build provisioningVM
on: push

jobs:
  build-VM:
    name: Build provisioningVM
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Where am I
        run: pwd
      - name: Run terraform init
        run: terraform init
      - name: Run terraform plan
        run: terraform plan
      - name: Run terraform apply -auto-approve
        run: terraform apply -auto-approve
